version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "github.com/caddy-dns/cloudflare"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/caddyserver/caddy/v2"
        update-types: ["version-update:semver-major"]
