---
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy-et-al:0.0.1
    container_name: caddy
    environment:
      ACME_AGREE: "true"
      CLAUDFLARE_EMAIL: ${CLAUDFLARE_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
