---
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CADDY_VERSION: 2.11.1
        L4_VERSION: v0.0.0-20260304182434-d882e9c2661d
        CF_VERSION: v0.0.0-20251204174556-6dc1fbb7e925
    image: caddy-et-al:latest
    container_name: caddy
    environment:
      ACME_AGREE: "true"
      CLAUDFLARE_EMAIL: ${CLAUDFLARE_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
